services:
  # Serviço PHP (Aplicação Springy)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: springy
        uid: 1000
    container_name: springy-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - springy-network
    depends_on:
      - mysql

  # Servidor Web Apache
  apache:
    image: php:8.1-apache
    container_name: springy-apache
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/apache/apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - app
    networks:
      - springy-network
    command: /bin/bash -c "a2enmod rewrite && apache2-foreground"

  # Banco de Dados MySQL
  mysql:
    image: mysql:8.0
    container_name: springy-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - springy-mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - springy-network
    ports:
      - "3306:3306"

  # Serviço phpMyAdmin (opcional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: springy-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - springy-network
    depends_on:
      - mysql

networks:
  springy-network:
    driver: bridge

volumes:
  springy-mysql-data:
    driver: local